const mongoose = require('mongoose')
const validator = require('validator')

/*
    When creating a account user MUST have
    - Name
    - Email
    - Password
    Token (will be generated by us)
*/

const userSchema = new mongoose.Schema({
    name: {
        type: String,
        required: true,
        trim: true,
        maxlength: 30
    },
    email: {
        type: String,
        required: true,
        trim: true,
        unique: true,
        validate(value){
            if(!validator.isEmail(value))
                throw new Error('Email is Invalid')
        }
    },
    
    password: {
        type: String,
        required: true,
        trime: true,
        minlength: 5,
        validate(value){
            if(value.toLowerCase().includes('password'))
                throw new Error('Password cannot contain "password"')
        }
    },

    tokens: [
        {
            token: {
                type: String,
                required: true
            }
        }
    ],

    profileImage: {
        type: Buffer
    },

    socailLink: {
            github: {
                type: String
            },
            twitter: {
                type: String
            },
            instagram: {
                type: String
            },
            youtube: {
                type: String
            },
            linkedin: {
                type: String
            }
    },

    about: {
        type: String,
        trim: true,
        maxlength: 30
    }

   
}, {
    timestamps: true
})


// restricitig not to send password and token in response
userSchema.methods.toJSON = function() {
    const userObject = this.toObject()
    delete userObject.password
    delete userObject.tokens
    return userObject
}

const User = mongoose.model('User', userSchema)

module.exports = User